### ISSUE TITLE
ascshd currently is not Windows friendly

### ISSUE THREAD

**Issue by jcward** [jcward/ascsh#6]
ascshd is a ruby script that uses fork, process IO, etc.  As-is, it doesn't work in Windows.  This is a problem because Flash Develop is a big potential user of ascsh.  However, perhaps FD itself can manage the ascsh process without the help of ascshd?  Did it manage the fcsh process?

**Comment by mnordine** [comment]
I'm currently testing using latest FlashDevelop build, and ascsh seems to be working fine.

https://github.com/fdorg/flashdevelop/commit/4e88ce2fcc489188af22333bf18be66dbe700800

**Comment by jcward** [comment]
I've updated the text of this bug to be more clear.  Since ascsh is now working via Flash Develop for Windows users, perhaps the ascshd server script (command-line workflow support in Windows) is not as important.  I'm closing this for now -- feel free to request ascshd support in the comments below.
