### ISSUE TITLE
Problems compiling on Windows 7

### ISSUE THREAD

**Issue by Koshmaar** [jcward/ascsh#8]
I've downloaded latest ant, setup the env variables, downloaded ascsh and run ant install as instructed. I got:

```
e:\FlashDevelop2\Tools\ascsh-master>ant install
Buildfile: e:\FlashDevelop2\Tools\ascsh-master\build.xml

compile:
    [javac] Compiling 2 source files to e:\FlashDevelop2\Tools\ascsh-master\build\classes
    [javac] e:\FlashDevelop2\Tools\ascsh-master\src\java\ascsh.java:1: package com.adobe.flash.compiler.clients doe
s not exist
    [javac] import com.adobe.flash.compiler.clients.MXMLC;
    [javac]                                        ^
    [javac] e:\FlashDevelop2\Tools\ascsh-master\src\java\ascsh.java:2: package com.adobe.flash.compiler.clients doe
s not exist
    [javac] import com.adobe.flash.compiler.clients.COMPC;
    [javac]                                        ^
    [javac] e:\FlashDevelop2\Tools\ascsh-master\src\java\ascsh.java:79: cannot find symbol
    [javac] symbol  : class MXMLC
    [javac] location: class ascsh
    [javac]         if (compiler instanceof MXMLC) {
    [javac]                                 ^
    [javac] e:\FlashDevelop2\Tools\ascsh-master\src\java\ascsh.java:81: cannot find symbol
    [javac] symbol  : class MXMLC
    [javac] location: class ascsh
    [javac]           exitCode = ((MXMLC)compiler).staticMainNoExit(args);
 (...)
    [javac] Note: e:\FlashDevelop2\Tools\ascsh-master\src\java\Commandline.java uses unchecked or unsafe operations
.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 9 errors

BUILD FAILED
e:\FlashDevelop2\Tools\ascsh-master\build.xml:14: Compile failed; see the compiler error output for details.

Total time: 1 second
```

What I'm doing wrong? :)

**Comment by jcward** [comment]
It can't find AIR SDK's `compiler.jar` on your class path.  Ensure that you've set `%AIR_HOME%` environment variable to point to your AIR sdk, i.e. `C:\air_sdk_3.9`

I should put a check in the build.xml to determine if the AIR_HOME environment variable is unset.

**Comment by Koshmaar** [comment]
I have set AIR_HOME to e:\FlashDevelop\Tools\flexsdk\ (flexsdk of FlashDevelop). It has some AIR SDK license files inside, so I thought that's also AIR. Then what should be the proper path? I couldn't find info on internet how to set it up.

Btw, how does this thing work with FD - should I run the server manually, or will it work automatically. Do I have to change something in FD settings to use it, or will it by default overwrite fcsh after runnig ant install? 

Sorry for so many questions :blush: there's little info about it, and I'm sure other people will have similiar questions. I think that after making this work for me, I will write short tutorial how to set it up.

**Comment by jcward** [comment]
For FlashDevelop, it will have ascsh support I think starting in the next release version (4.6).  I was working with Philippe Elsass on it.  He said the `ascsh.jar` may be delivered with the installer package so it wouldn't require any git or compiler knowledge.  If it isn't delivered by Flash Develop, you simply place the `ascsh.jar` in your AIR SDK lib folder and startup FlashDevelop.  You don't need to compile it as `ascsh.jar` is available in the repo under `dist/ascsh.jar`

BTW, the Flex SDK is different than the AIR SDK.  You need the AIR SDK from Adobe (http://www.adobe.com/devnet/air/air-sdk-download.html) to use ascsh.  The Flex SDK already has fast compilation via fcsh.

Cheers!
-Jeff

**Comment by jcward** [comment]
See:  http://www.flashdevelop.org/community/viewtopic.php?f=1&t=11537

**Comment by elsassph** [comment]
As far as Flashdevelop is concerned, ascsh.jar is now bundled and automatically copied in the AIR SDK if it's missing.

**Comment by jcward** [comment]
Verified that ant build worked on Windows 7.  Closing.  =)

**Comment by Koshmaar** [comment]
Ok, I have downloaded newest dev FlashDevelop (4.6.0.71), the ascsh.jar is in the Tools\flexlibs\lib\ directory, I launch the FD build process and it still uses the fcsh. What else should I do to make this work?

Do I really have to download separate this gigantic AIR SDK? I think that I already have it - my SDK options tells me that I have Flex 4.6.0 and AIR 3.9. Also, I'm able to compile AIR apps in FD. But if it's still needed, where should I install it, in the same directory as my e:\FlashDevelop\Tools\flexsdk ?

**Comment by jcward** [comment]
Hi Koshmaar,

If it's using fcsh, it means your proejct is using the Flex SDK.  You need to tell your project to use the AIR SDK.  I think it's under project properties.  If AIR SDK isn't an option, you need to setup FD to find the AIR SDK.

Remember, the whole purpose of ascsh is to provide fcsh-like speed for the AIR SDK, as the AIR SDK provides telemetry and the newest compiler features, like [Inline], which the Flex SDK does not.

If you don't need -telemetry or [Inline], Flex SDK will work just fine for you.

Best,
-Jeff

**Comment by elsassph** [comment]
fcsh.jar takes precedence over ascsh.jar - maybe it should be the opposite?

**Comment by jcward** [comment]
Does FD install AIR SDK by default?  Does Flex SDK take precedence over AIR SDK?  Or does it depend on project settings?

It's really about which SDK is active, then use fcsh or ascsh accordingly.

**Comment by elsassph** [comment]
FD offers to install by default the Flex SDK and the AIR SDK as 2 distinct SDKs - however we merge the AIR SDK in the Flex SDK to update the AIR target. We'd have to do some hacks to let you use the legacy compiler...

**Comment by jcward** [comment]
Ah.  In a merged directory, if you're preferring the AIR SDK, I assume you should prefer ascsh.

Calling `fcsh.jar` will get you the old Flex compiler (from `lib/mxmlc.jar`), while calling `ascsh.jar` will use the new compiler (`lib/compiler.jar`).  BTW, calling `bin/mxmlc.bat` executable will get the new compiler because AIR SDK overwrites Flex SDK's `bin/mxmlc.bat`.

**Comment by Koshmaar** [comment]
Thank you Jeff and Philippe. Ah, I was under the impression that it was for Flex... or in other words, that I could create normal Flash Player games for web. But even using AIR that still should be possible, right? Because the AIR projects are actually .exe and .swf, the former embedding the latter. All I need is .swf.

Why I'm after this solution is because of speed - I read (http://www.bytearray.org/?p=4789) that the newer compiler uses multithreading, wchich for my 4 core CPU and this quite big project would be a godsend. So I need faster incremental compilation. Inlines wouldn't hurt also :) 

As for the discussion on how this feature should be implemented in FD, I would vote for a checkbox in Settings, that will steer this.

**Comment by jcward** [comment]
Yes, either compiler will get you a .SWF as the output, and you can use that .swf on the web or in an actual AIR app (well, depending on whether it uses classes only available in AIR or not).  The AIR SDK simply has the latest compiler, so I presume, should always be preferred if it's there, no matter where you plan on using the SWF.

The AIR / asc2.0 compiler may be faster, but it isn't memory resident outside of Flash Builder... which is where ascsh comes in.  If you're already using fcsh, ascsh won't necessarily get you faster compile times, but you would get the other goodies (telemetry, Inline, etc) at roughly the same compile-times.  Without ascsh, AIR SDK would be slower by comparison.

**Comment by elsassph** [comment]
First both Flex SDK's mxmlc compiler and AIR SDK's asc2 compiler can
compile a SWF for either web or AIR runtime.

Then AIR SDK, which is included but not up to date in the Flex SDK,
provides the tool needed to package an AIR app.

It is not possible to just use asc2 compiler in place of the Flex SDK's
because it's not a drop-in replacement:
- slightly different compiler options,
- slightly different AS3 parser and typing rules (asc2 is a bit stricter),
- asc2 doesn't support MXML at all.

**Comment by Koshmaar** [comment]
Ok, so my best bet for quicker compilations is to buy a faster CPU ;) Too bad, but during my recent test I got impression that even fcsh is not single threaded, because I observed that during compilation all 4 cores are working at around 50-70%, so beating that by as ascsh might not be possible, or the gain will be small. In that case jumping hoops in configuring evninroment and making changes to project is not worth my time :( Thank you for help, Jeff and Philippe. I hope this thread will also help others.

**Comment by jcward** [comment]
Koshmaar, what compile times are you seeing and how big is your project?  I have a 40k+ line mobile app (mostly as3 with a couple SWCs) that compiles in 3 seconds using ascsh (first cold compile is 15 seconds.)  It's not great, but it's usable.  My cpu is an Intel i7-3770.

Packaging times, on the other hand, are a real pain, which has led me to investigate live code and asset reloading -- perhaps another possibility for you...

**Comment by Koshmaar** [comment]
So I have around 700kb of source in 50+ files, not counting source libraries (like greensock, Flixel, which is another 800kb) and maybe 1-2-3 swcs. I also have cold compile taking around 10-15s, while the incremental takes 2-3s. It's not bad (on Phenom II X4 3Ghz), but I'd love to have it start instantly :) because sometime's I'm tweaking one variable, or testing something, and I do a lot of edit/compile cycles. I don't think it's possible to optimize it (by removing my code). 

As for live coding... I tried COLT demo, but it didn't work for me. So most likely in a few months I will upgrade MB and buy more modern CPU strong in single core (i3 or i5). I haven't heard of asset reloading in flash, I use embeds all over the place, and fortunately I rarely need to tweak assets.

I make a browser game, so as soon as I have swf I am good :) No packaging needed.

**Comment by gene-pavlovsky** [comment]
I'm using AIR SDK 18.0.0 with FlashDevelop 5 and ascsh. 
My project is 16k lines, plus three SWCs (starling+feathers+theme).
Cold compile takes 6-7 s, and incremental compiles about 4-5 s, I've expected the incremental compile time to be significantly lower than the cold compile (that's what I experienced before, when I was using the Flex SDK and fcsh), that's quite strange. Any advice?
CPU is a mobile Core i7.
