### ISSUE TITLE
When using with FlashDevelop - Compiler Errors don't report to the Results Panel

### ISSUE THREAD

**Issue by BigPhilCombo** [jcward/ascsh#9]
When I use ascsh with FlashDevelop, incremental compilation works fine but any compiler errors do not get reported to the results panel.  The errors still show up in the Output panel so you can see what went wrong, but without outputting to the Results panel, a user cannot double click and go directly to a compiler error's location in code.

**Comment by elsassph** [comment]
There really are no differences in the Output panel?

**Comment by jcward** [comment]
pchertok - do you know if errors went to the results panel when using fcsh?  Since the shells don't exit (hence don't provide an exit code), there must be a specific string FD is looking for...

Hmm, testing from the commandline, fcsh output is:

```
(fcsh) compile 1
Loading configuration file /opt/flex_sdk_4.6/frameworks/flex-config.xml
Recompile: /home/admin/dev/air_tests/bounds_test/Main.as
Reason: The source file or one of the included files has been updated.
Files changed: 1 Files affected: 0
/home/admin/dev/air_tests/bounds_test/Main.as(14): col: 7 Error: Access of undefined property foo.

      foo;
      ^

(fcsh) 
```

ascsh output is:

```
(fcsh) compile 1
Loading configuration: /opt/air_sdk_3.9/frameworks/flex-config.xml

/home/admin/dev/air_tests/bounds_test/Main.as:14
Error: Access of possibly undefined property foo.
      foo;
      ^

Compile status: 2
(fcsh) 
```

What is FD looking for?

**Comment by jcward** [comment]
Ahh, the underlying compiler error format seems to have changed for Air's ASC 2.0 compiler:

```
>$AIR_HOME/bin/mxmlc Main.as -debug
Loading configuration: /opt/air_sdk_3.9/frameworks/flex-config.xml

/home/admin/dev/air_tests/bounds_test/Main.as:14
Error: Access of possibly undefined property foo.
      foo;
      ^

>$FLEX_HOME/bin/mxmlc Main.as -debug
Loading configuration file /opt/flex_sdk_4.6/frameworks/flex-config.xml
/home/admin/dev/air_tests/bounds_test/Main.as(14): col: 7 Error: Access of undefined property foo.

      foo;
      ^
```

**Comment by BigPhilCombo** [comment]
The output does seem slightly different but it appears like jcward has figured that out already.

**Comment by jcward** [comment]
Philippe, since our plan to date has been to make `ascsh` mimic `fcsh`, we could easily RegEx replace the error format in `ascsh.java` if you'd prefer that solution.  In other words, I'm happy to handle this on my end.  =)

```
:\d+:\nError: --->  ($1): col: # Error:
```

Is the column number important?

**Comment by jcward** [comment]
Ooh, I guess I'd have to capture/filter System.println somehow...  Surely Java can do that...  Perhaps:

http://stackoverflow.com/questions/9852774/has-anyone-played-with-nio-pipes-to-filter-intercept-system-out

**Comment by elsassph** [comment]
This issue is now fixed (by reformatting ascsh error output), read the instructions to update the JAR in FlashDevelop:
http://www.flashdevelop.org/community/viewtopic.php?f=6&t=11614&p=51235#p51235
